### ISSUE TITLE
您好，我在安装时碰到了问题

### ISSUE THREAD

**Issue by TrepangCat** [Anyk00/arknights-mower#3]
Traceback (most recent call last):
  File "webview_ui.py", line 223, in <module>
  File "webview\__init__.py", line 155, in start
  File "webview\guilib.py", line 119, in initialize
  File "webview\guilib.py", line 71, in try_import
  File "webview\guilib.py", line 60, in import_winforms
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "webview\platforms\winforms.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "clr.py", line 6, in <module>
  File "pythonnet\__init__.py", line 143, in load
  File "clr_loader\types.py", line 94, in get_function
  File "clr_loader\types.py", line 58, in __init__
  File "clr_loader\netfx.py", line 47, in _get_callable
RuntimeError: Failed to resolve Python.Runtime.Loader.Initialize from D:\Program Files\arknights_mower\2024.02.5\_internal\pythonnet\runtime\Python.Runtime.dll

**Comment by Anyk00** [comment]
安装可以参考这篇博客https://blog.zhaozuohong.vip/2023/08/02/run-arknights-mower-from-source/
如果使用的是我fork的代码请使用python3.8版本，若使用的是mower的dev_shawn分支代码则按照博客安装即可。
推荐使用mower的dev_shawn分支，我这边很久没改动了。
